server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:15432/postgres?schema=public
    username: postgres
    password: testtesttest
  cloud:
    stream:
      function:
        definition: inventoryProcessor
      bindings:
        inventoryProcessor-in-0:
          destination: order-event
        inventoryProcessor-out-0:
          destination: inventory-event
      kafka:
        binder:
          replication-factor: 1

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.kafka: WARN
